@startuml   
start
:Staff truy cập danh sách yêu cầu đăng ký trang sức;
:Hệ thống hiển thị danh sách các yêu cầu;
:Staff chọn yêu cầu cần gửi thông báo;
:Hệ thống hiển thị thông tin chi tiết của yêu cầu;
:Staff nhấn nút "Yêu cầu gửi trang sức";
:Hệ thống cập nhật trạng thái yêu cầu;
:Hệ thống gửi thông báo yêu cầu gửi trang sức đến Seller;
stop
@enduml