@startuml   ViewProfile
start
:Người dùng truy cập trang hồ sơ cá nhân;
:Hệ thống kiểm tra trạng thái đăng nhập;
if (Người dùng đã đăng nhập?) then (Yes)
  :Hệ thống truy vấn thông tin cá nhân;
  :Hệ thống hiển thị thông tin cá nhân;
else (No)
  :Hệ thống chuyển hướng đến trang đăng nhập;
endif
stop
@enduml