@startuml   
start
:Manager truy cập trang quản lý phiên đấu giá;
:Hệ thống hiển thị danh sách phiên đấu giá;
:Manager chọn phiên đấu giá cần thêm trang sức;
:Hệ thống hiển thị danh sách trang sức đã được duyệt;
:Manager chọn (các) trang sức;
:Manager nhấn nút "Thêm vào phiên đấu giá";
:Hệ thống cập nhật danh sách trang sức cho phiên đấu giá;
:Hệ thống thông báo thành công;
stop
@enduml 
