@startuml   
start
:Giao dịch được xác nhận "Đã thanh toán";
:Staff nhận được thông báo bàn giao trang sức;
:Staff liên hệ với Buyer để sắp xếp bàn giao;
:(Thực hiện bàn giao trang sức);
:Staff cập nhật trạng thái giao dịch thành "Đã bàn giao";
:Hệ thống thông báo cho Buyer và Seller;
stop
@enduml 
