# Generated by Django 5.1.4 on 2025-01-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_rate', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
