# Generated by Django 5.1.4 on 2024-12-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_rate', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='JCoinManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_jcoin', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
