# Generated by Django 5.1.4 on 2024-12-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JCoinManagement',
        ),
    ]
