# Generated by Django 5.1.4 on 2025-01-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('jewelry_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='jewelry/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='jewelry/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='jewelry/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUCTIONING', 'Auctioning'), ('SOLD', 'Sold'), ('DELIVERED', 'Delivered'), ('NO_BIDS', 'No Bids')], default='PENDING', max_length=20)),
                ('preliminary_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('seller_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
