# Generated by Django 5.1.4 on 2024-12-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='preliminary_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='seller_approved',
            field=models.BooleanField(default=False),
        ),
    ]
