# Generated by Django 5.1.4 on 2024-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
