# Generated by Django 5.1.4 on 2024-12-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUCTIONING', 'Auctioning'), ('SOLD', 'Sold'), ('DELIVERED', 'Delivered'), ('NO_BIDS', 'No Bids')], default='PENDING', max_length=20),
        ),
    ]
