# Generated by Django 5.1.4 on 2024-12-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0003_remove_jewelry_is_approved_alter_jewelry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='jewelry/'),
        ),
    ]
