# Generated by Django 5.1.4 on 2024-12-23 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='jewelry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry.jewelry'),
        ),
    ]
