@startuml   
actor "Member (Seller)" as Seller
participant "Hệ thống" as System

activate Seller
Seller -> System: Gửi yêu cầu đăng ký trang sức(thông tin trang sức, hình ảnh)
activate System
System --> Seller: Hiển thị form đăng ký
deactivate System
Seller -> System: Điền thông tin trang sức, tải lên hình ảnh
activate System
System -> System: Kiểm tra thông tin
alt Thông tin hợp lệ
    System -> System: Lưu thông tin trang sức
    System --> Seller: Thông báo gửi yêu cầu thành công
else Thông tin không hợp lệ
    System --> Seller: Thông báo lỗi
end
deactivate System
deactivate Seller
@enduml