@startuml   
actor Staff
participant "Hệ thống" as System
participant "Member (Seller)" as Seller

activate Staff
Staff -> System: Gửi thông báo định giá cuối cùng
activate System
System -> System: Lấy thông tin định giá cuối cùng
System --> Seller: Thông báo định giá cuối cùng
System --> Staff: Thông báo gửi thành công
deactivate System
deactivate Staff
@enduml