@startuml   
actor User
participant "Hệ thống" as System

activate User
User -> System: Gửi yêu cầu xem hồ sơ cá nhân
activate System
System --> User: Hiển thị thông tin cá nhân
deactivate System
deactivate User
@endumls