@startuml   
actor Manager
participant "Hệ thống" as System

activate Manager
Manager -> System: Gửi yêu cầu phân công nhân viên
activate System
System --> Manager: Hiển thị danh sách phiên đấu giá
deactivate System
Manager -> System: Chọn phiên đấu giá
activate System
System --> Manager: Hiển thị danh sách nhân viên
deactivate System
Manager -> System: Chọn nhân viên
activate System
System -> System: Cập nhật thông tin phân công
System --> Manager: Thông báo phân công thành công
deactivate System
deactivate Manager
@enduml