@startuml   
actor "Manager/Staff" as User
participant "Hệ thống" as System

activate User
User -> System: Gửi yêu cầu theo dõi phiên đấu giá
activate System
System --> User: Hiển thị danh sách phiên đấu giá
deactivate System
User -> System: Chọn phiên đấu giá
activate System
System --> User: Hiển thị thông tin chi tiết của phiên đấu giá (giá thầu hiện tại, thời gian còn lại, v.v.)
deactivate System
deactivate User
@enduml