@startuml   
actor User
participant "Hệ thống" as System

activate User
User -> System: Yêu cầu xem thông tin trang sức
activate System
System -> System: Lấy thông tin trang sức
System --> User: Hiển thị thông tin trang sức
deactivate System
deactivate User
@enduml