@startuml   
actor User
participant "Hệ thống" as System

activate User
User -> System: Gửi yêu cầu xem blog
activate System
System -> System: Lấy danh sách bài viết
System --> User: Hiển thị danh sách bài viết
deactivate System
User -> System: Chọn xem chi tiết bài viết
activate System
System -> System: Lấy nội dung bài viết
System --> User: Hiển thị nội dung bài viết
deactivate System
deactivate User
@enduml