@startuml   
actor Staff
participant "Hệ thống" as System

activate Staff
Staff -> System: Gửi yêu cầu định giá cuối cùng
activate System
System --> Staff: Hiển thị thông tin yêu cầu
deactivate System
Staff -> System: Nhập giá trị định giá cuối cùng
activate System
System -> System: Lưu giá trị định giá cuối cùng
System --> Staff: Thông báo gửi định giá cuối cùng thành công
deactivate System
deactivate Staff
@enduml