@startuml   
actor User
participant "Hệ thống" as System

activate User
User -> System: Gửi yêu cầu đăng nhập(tên đăng nhập, mật khẩu)
activate System
System -> System: Kiểm tra thông tin đăng nhập
alt Thông tin chính xác
    System --> User: Chuyển hướng đến trang chính (theo vai trò)
else Thông tin không chính xác
    System --> User: Thông báo lỗi
end
deactivate System
deactivate User
@enduml