@startuml   
participant "Hệ thống" as System

activate System
System -> System: Xác định phiên đấu giá kết thúc
System -> System: Lấy danh sách giá thầu của phiên đấu giá
System -> System: Xác định giá thầu cao nhất
System -> System: Xác định người thắng cuộc (Buyer đặt giá thầu cao nhất)
System -> System: Cập nhật thông tin phiên đấu giá (người thắng, giá thắng cuộc)
System -> System: Gửi thông báo đến các bên liên quan
deactivate System
@enduml