@startuml   
actor "Member (Buyer/Seller)" as Member
participant "Hệ thống" as System

activate Member
Member -> System: Gửi yêu cầu đăng ký(thông tin đăng ký)
activate System
System --> Member: Hiển thị form đăng ký
deactivate System
Member -> System: Điền thông tin đăng ký
activate System
System -> System: Kiểm tra thông tin
alt Thông tin hợp lệ
    System -> System: Tạo tài khoản mới
    System --> Member: Thông báo đăng ký thành công
else Thông tin không hợp lệ
    System --> Member: Thông báo lỗi
end
deactivate System
deactivate Member

@enduml