@startuml   
actor Staff
participant "Hệ thống" as System
participant "Member (Seller)" as Seller

activate Staff
Staff -> System: Chọn yêu cầu cần gửi thông báo
activate System
System --> Staff: Hiển thị thông tin yêu cầu
deactivate System
Staff -> System: Gửi yêu cầu gửi trang sức đến Seller
activate System
System -> System: Cập nhật trạng thái yêu cầu
System --> Seller: Thông báo yêu cầu gửi trang sức
System --> Staff: Thông báo gửi yêu cầu thành công
deactivate System
deactivate Staff
@enduml