@startuml   
actor Manager
participant "Hệ thống" as System

activate Manager
Manager -> System: Gửi yêu cầu chọn trang sức cho phiên đấu giá
activate System
System --> Manager: Hiển thị danh sách phiên đấu giá
deactivate System
Manager -> System: Chọn phiên đấu giá
activate System
System --> Manager: Hiển thị danh sách trang sức đã được duyệt
deactivate System
Manager -> System: Chọn trang sức
activate System
System -> System: Cập nhật danh sách trang sức cho phiên đấu giá đã chọn
System --> Manager: Thông báo cập nhật thành công
deactivate System
deactivate Manager
@enduml