# Generated by Django 5.1.4 on 2024-12-31 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='jewelry_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='winning_bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
